name: Deploy Worker
on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add Header
      run: cp ${{ github.workspace }}/dist/worker.js ${{ github.workspace }}/dist/worker-original.js && echo -e "/*!\n  * v2ray Subscription Worker (${{ github.sha }})\n  * Copyright 2024 Vahid Farid (https://twitter.com/vahidfarid)\n  * Licensed under GPLv3 (https://github.com/vfarid/v2ray-worker/blob/main/Licence.md)\n  */\n\n$(cat ${{ github.workspace }}/dist/worker.js)" > ${{ github.workspace }}/dist/worker.js

    - name: Change KV Name
      run: sed -i s/KV_NAME/${{ secrets.KV_NAME }}/g wrangler.toml

    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}

    # - name: Deploy
      # run: sed -i s/KV_NAME/${{ secrets.KV_NAME }}/g wrangler.toml
      # with:
      #   apiToken: ${{ secrets.CF_API_TOKEN }}
      #   accountId: ${{ secrets.CF_ACCOUNT_ID }}
